import { test } from "node:test";
import assert from "node:assert/strict";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { execFileSync } from "child_process";
import { orderFilesRoundRobin, runScanWalk } from "../src/scan";
import {
  clearHistory,
  getAllAnsweredConceptTags,
  getConceptTagGlobal,
  getScannedFilePaths,
  insertEvent,
  openStore,
} from "../src/store";
import { testConfig } from "./helpers";

/**
 * Headless tests for `grasp scan`'s file-walk logic — ordering, capping,
 * resumability, the mechanical ignore/generated-file/binary/oversized
 * skips, and the shared-memoization hard requirement — all exercised
 * directly against `runScanWalk`/`orderFilesRoundRobin`, without going
 * through the interactive review UI (which needs a real pty — see
 * scanPty.test.ts for that layer). See DECISIONS.md's `grasp scan` entries
 * for the design this verifies.
 */

const FIXTURE_CLAUDE_DIR = path.resolve(process.cwd(), "test/fixtures/mock-claude");

function withMockClaude(env: Record<string, string>, fn: () => void): void {
  const originalPath = process.env.PATH;
  const originalEnv: Record<string, string | undefined> = {};
  for (const key of Object.keys(env)) originalEnv[key] = process.env[key];
  process.env.PATH = `${FIXTURE_CLAUDE_DIR}:${originalPath}`;
  Object.assign(process.env, env);
  try {
    fn();
  } finally {
    process.env.PATH = originalPath;
    for (const key of Object.keys(env)) {
      if (originalEnv[key] === undefined) delete process.env[key];
      else process.env[key] = originalEnv[key];
    }
  }
}

function mkTempDir(prefix: string): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), prefix));
}

function git(cwd: string, args: string[]): void {
  execFileSync("git", args, { cwd, stdio: "pipe" });
}

/**
 * A real git repo with tracked files spread across three top-level
 * directories plus a root-level file — enough to prove round-robin
 * directory spreading actually happened, not just plausible-looking file
 * counts. Also includes one lockfile (baseline-ignored) and one
 * self-declared generated file, both under their own directory, to prove
 * the mechanical skips work during a real walk without ever reaching the
 * judge.
 */
function initFixtureRepo(): string {
  const repo = mkTempDir("grasp-test-scan-repo-");
  git(repo, ["init", "-q"]);
  git(repo, ["config", "user.email", "test@example.com"]);
  git(repo, ["config", "user.name", "Test"]);

  const write = (rel: string, content: string) => {
    const full = path.join(repo, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content);
  };

  write("alpha/one.ts", "export function alphaOne() {\n  return 1;\n}\n");
  write("alpha/two.ts", "export function alphaTwo() {\n  return 2;\n}\n");
  write("beta/one.ts", "export function betaOne() {\n  return 3;\n}\n");
  write("beta/two.ts", "export function betaTwo() {\n  return 4;\n}\n");
  write("gamma/one.ts", "export function gammaOne() {\n  return 5;\n}\n");
  write("root.ts", "export function root() {\n  return 6;\n}\n");
  write("alpha/package-lock.json", '{"lockfileVersion": 1}');
  write("beta/generated.ts", "// Code generated by protoc-gen-ts. DO NOT EDIT.\nexport const x = 1;\n");

  git(repo, ["add", "-A"]);
  git(repo, ["commit", "-q", "-m", "initial"]);
  return repo;
}

function tempDbPath(): string {
  return path.join(mkTempDir("grasp-test-scan-db-"), "history.db");
}

// --- orderFilesRoundRobin: pure ordering logic ------------------------------

test("orderFilesRoundRobin: interleaves across top-level directories instead of exhausting one first", () => {
  const paths = ["a/1.ts", "a/2.ts", "a/3.ts", "b/1.ts", "c/1.ts", "c/2.ts"];
  const ordered = orderFilesRoundRobin(paths);
  const dirs = ordered.map((p) => p.split("/")[0]);
  // Round-robin: a, b, c, a, c (b exhausted after its one file), a.
  assert.deepEqual(dirs, ["a", "b", "c", "a", "c", "a"]);
});

test("orderFilesRoundRobin: a root-level file gets its own group, not merged with any subdirectory", () => {
  const ordered = orderFilesRoundRobin(["root.ts", "a/1.ts"]);
  assert.equal(ordered.length, 2);
  assert.ok(ordered.includes("root.ts"));
  assert.ok(ordered.includes("a/1.ts"));
});

test("orderFilesRoundRobin: every input path appears exactly once in the output, none lost or duplicated", () => {
  const paths = ["a/1.ts", "a/2.ts", "b/1.ts", "b/2.ts", "b/3.ts", "c/1.ts"];
  const ordered = orderFilesRoundRobin(paths);
  assert.deepEqual([...ordered].sort(), [...paths].sort());
});

// --- runScanWalk: capping, ordering-in-practice, resumability --------------

test("runScanWalk: a capped run stops partway and actually spreads coverage across more than one top-level directory", () => {
  const repo = initFixtureRepo();
  const db = openStore(tempDbPath());
  const config = testConfig({ scanQuestionsCap: 3 });
  const sessionId = "scan-cap-test";

  withMockClaude({ GRASP_TEST_MOCK_MODE: "normal", GRASP_TEST_MOCK_COST: "0.001" }, () => {
    const ordered = orderFilesRoundRobin(["alpha/one.ts", "alpha/two.ts", "beta/one.ts", "beta/two.ts", "gamma/one.ts", "root.ts"]);
    const result = runScanWalk(db, repo, sessionId, config, ordered, false);
    assert.equal(result.capped, true, "the walk must stop once the cap is hit, not exhaust the whole list");
  });

  const scanned = getScannedFilePaths(db, repo);
  assert.equal(scanned.size, 3, "exactly 3 files should be marked scanned — one per real question up to the cap");
  const dirsCovered = new Set([...scanned].map((p) => p.split("/")[0]));
  assert.ok(dirsCovered.size > 1, `expected coverage across more than one top-level directory, got only: ${[...dirsCovered]}`);
  db.close();
});

test("runScanWalk: full=true bypasses the cap entirely, walking every file regardless of questionsPerSessionCap-style limits", () => {
  const repo = initFixtureRepo();
  const db = openStore(tempDbPath());
  // A cap of 1 would normally stop the walk after the first real question —
  // full=true must ignore it completely.
  const config = testConfig({ scanQuestionsCap: 1 });
  const files = ["alpha/one.ts", "alpha/two.ts", "beta/one.ts", "gamma/one.ts"];

  withMockClaude({ GRASP_TEST_MOCK_MODE: "normal", GRASP_TEST_MOCK_COST: "0.001" }, () => {
    const result = runScanWalk(db, repo, "scan-full-test", config, orderFilesRoundRobin(files), true);
    assert.equal(result.capped, false);
    assert.equal(result.filesWalked, files.length);
  });

  assert.equal(getScannedFilePaths(db, repo).size, files.length);
  db.close();
});

test("runScanWalk: a second run resumes from unscanned files, never re-asking about already-covered ones", () => {
  const repo = initFixtureRepo();
  const dbPath = tempDbPath();
  const allSourceFiles = ["alpha/one.ts", "alpha/two.ts", "beta/one.ts"];

  const db1 = openStore(dbPath);
  withMockClaude({ GRASP_TEST_MOCK_MODE: "normal", GRASP_TEST_MOCK_COST: "0.001" }, () => {
    runScanWalk(db1, repo, "scan-run-1", testConfig({ scanQuestionsCap: 1 }), orderFilesRoundRobin(allSourceFiles), false);
  });
  const scannedAfterRun1 = getScannedFilePaths(db1, repo);
  assert.equal(scannedAfterRun1.size, 1);
  db1.close();

  const db2 = openStore(dbPath);
  const unscanned = allSourceFiles.filter((f) => !getScannedFilePaths(db2, repo).has(f));
  assert.equal(unscanned.length, 2, "the resumed run must see exactly the files the first run didn't cover");
  withMockClaude({ GRASP_TEST_MOCK_MODE: "normal", GRASP_TEST_MOCK_COST: "0.001" }, () => {
    const result = runScanWalk(db2, repo, "scan-run-2", testConfig({ scanQuestionsCap: 999 }), orderFilesRoundRobin(unscanned), false);
    assert.equal(result.filesWalked, 2);
  });
  const scannedAfterRun2 = getScannedFilePaths(db2, repo);
  assert.equal(scannedAfterRun2.size, 3, "all 3 files scanned across the two runs combined");

  const events = db2.prepare(`SELECT COUNT(*) AS n FROM events WHERE session_id IN ('scan-run-1', 'scan-run-2') AND question_type IS NOT NULL`).get() as { n: number };
  assert.equal(events.n, 3, "3 distinct real questions total, one per file, none re-asked");
  db2.close();
});

test("runScanWalk: ignore patterns and generated-file detection skip files without ever invoking claude", () => {
  const repo = initFixtureRepo();
  const db = openStore(tempDbPath());
  const config = testConfig({ scanQuestionsCap: 999 });

  // No mock claude on PATH at all — proves these two files never reach a
  // judge call. If either did, execFileSync("claude", ...) would fail
  // outright (no such binary), which would surface as an "error" miss row
  // instead of the two files being silently marked scanned with zero rows.
  const result = runScanWalk(db, repo, "scan-ignore-test", config, ["alpha/package-lock.json", "beta/generated.ts"], false);
  assert.equal(result.filesWalked, 2);

  const scanned = getScannedFilePaths(db, repo);
  assert.ok(scanned.has("alpha/package-lock.json"));
  assert.ok(scanned.has("beta/generated.ts"));

  const eventCount = (db.prepare(`SELECT COUNT(*) AS n FROM events`).get() as { n: number }).n;
  assert.equal(eventCount, 0, "neither file should have produced any events row — both were mechanically skipped");
  db.close();
});

test("runScanWalk: a binary file is skipped (marked scanned, no judge call)", () => {
  const repo = initFixtureRepo();
  fs.writeFileSync(path.join(repo, "binary.dat"), Buffer.from([0x00, 0x01, 0x02, 0xff, 0x00]));
  const db = openStore(tempDbPath());
  const config = testConfig({ scanQuestionsCap: 999 });

  runScanWalk(db, repo, "scan-binary-test", config, ["binary.dat"], false);

  assert.ok(getScannedFilePaths(db, repo).has("binary.dat"));
  const eventCount = (db.prepare(`SELECT COUNT(*) AS n FROM events`).get() as { n: number }).n;
  assert.equal(eventCount, 0);
  db.close();
});

test("runScanWalk: a failed judge call (error) leaves the file unscanned for retry, not lost", () => {
  const repo = initFixtureRepo();
  const db = openStore(tempDbPath());
  const config = testConfig({ scanQuestionsCap: 999 });

  withMockClaude({ GRASP_TEST_MOCK_MODE: "error" }, () => {
    runScanWalk(db, repo, "scan-fail-test", config, ["alpha/one.ts"], false);
  });

  assert.equal(getScannedFilePaths(db, repo).has("alpha/one.ts"), false, "a failed attempt must not be marked scanned");
  const missRow = db.prepare(`SELECT miss_reason, source FROM events WHERE session_id = 'scan-fail-test'`).get() as any;
  assert.equal(missRow.miss_reason, "error");
  assert.equal(missRow.source, "scan");
  db.close();
});

// --- the one hard, non-negotiable requirement: shared memoization ----------

test("runScanWalk: a concept mastered via a live diff question is skipped during a scan (shared memoization)", () => {
  const repo = initFixtureRepo();
  const db = openStore(tempDbPath());
  const config = testConfig({ scanQuestionsCap: 999 });

  // Seed a diff-sourced, answered concept tag — exactly what a real
  // `grasp review` answer produces (source defaults to "diff").
  insertEvent(
    db,
    {
      timestamp: new Date().toISOString(),
      repo,
      sessionId: "real-cc-session",
      diffHash: "abc",
      diffSummary: "1 file changed",
      questionConcept: "What is a mutex?",
      questionInstance: "Why did this diff use one?",
      questionType: "both",
      generationSource: "headless-claude-p",
      missReason: null,
      answerConcept: "a mutual exclusion lock",
      answerInstance: "to protect shared state",
      skipped: false,
      skipReason: null,
      costUsd: 0.001,
      diffFiles: [],
    },
    [{ tag: "mutex-vs-channel", answered: true }]
  );
  assert.equal(getConceptTagGlobal(db, "mutex-vs-channel", true).length, 1, "sanity check: the concept is recorded as answered");

  // The mock's "brand-new-concept-no-question" mode conveniently returns a
  // FIXED tag name — swap it for "mutex-vs-channel" via a small local mock
  // instead, so this test exercises the real already-answered branch of
  // runScanFileGeneration (instance-only, no concept question) rather than
  // the contract-violation branch that mode is actually for.
  const mockClaudeDir = fs.mkdtempSync(path.join(os.tmpdir(), "grasp-test-scan-memo-mock-"));
  fs.writeFileSync(
    path.join(mockClaudeDir, "claude"),
    `#!/usr/bin/env node
const result = {
  worthAsking: true,
  conceptTag: "mutex-vs-channel",
  questionConcept: "should never be asked again",
  questionInstance: "instance question about this file",
  sampleAnswerConcept: "should not appear",
  sampleAnswerInstance: "sample instance answer",
  conceptExplanation: "explanation",
  citedLineStart: 1,
  citedLineEnd: 2
};
process.stdout.write(JSON.stringify({ total_cost_usd: 0.001, result: JSON.stringify(result), is_error: false }));
`,
    { mode: 0o755 }
  );

  const originalPath = process.env.PATH;
  process.env.PATH = `${mockClaudeDir}:${originalPath}`;
  try {
    runScanWalk(db, repo, "scan-memo-test", config, ["alpha/one.ts"], false);
  } finally {
    process.env.PATH = originalPath;
  }

  const row = db.prepare(`SELECT question_concept, question_instance, question_type, sample_answer_concept FROM events WHERE session_id = 'scan-memo-test'`).get() as any;
  assert.equal(row.question_type, "instance", "the concept question must be suppressed — this concept was already mastered via a diff question");
  assert.equal(row.question_concept, null);
  assert.equal(row.sample_answer_concept, null);
  assert.equal(row.question_instance, "instance question about this file");
  db.close();
});

test("runScanWalk: a concept mastered via a scan question is skipped for a later diff-side generation (shared memoization, the other direction)", () => {
  const db = openStore(tempDbPath());
  // Seed a scan-sourced, answered concept tag.
  insertEvent(
    db,
    {
      timestamp: new Date().toISOString(),
      repo: "/tmp/whatever-repo",
      sessionId: "scan-abc123",
      diffHash: null,
      diffSummary: "some/file.ts",
      questionConcept: "What is recursion?",
      questionInstance: "Where does this file use it?",
      questionType: "both",
      generationSource: "headless-claude-p",
      missReason: null,
      answerConcept: "a function calling itself",
      answerInstance: "in the tree-walk helper",
      skipped: false,
      skipReason: null,
      costUsd: 0.001,
      diffFiles: null,
      source: "scan",
    },
    [{ tag: "recursion", answered: true }]
  );

  // getAllAnsweredConceptTags (what the diff-side judge prompt reads to
  // avoid re-teaching) must include this tag with no source filter at all.
  const answered: string[] = getAllAnsweredConceptTags(db);
  assert.ok(answered.includes("recursion"), "a concept mastered via grasp scan must show up in the diff side's own already-answered list");
  db.close();
});

// --- reset history clears scan progress too ---------------------------------

test("clearHistory: also wipes scan_progress, so a reset repo can be scanned from scratch", () => {
  const repo = initFixtureRepo();
  const db = openStore(tempDbPath());
  withMockClaude({ GRASP_TEST_MOCK_MODE: "normal", GRASP_TEST_MOCK_COST: "0.001" }, () => {
    runScanWalk(db, repo, "scan-reset-test", testConfig({ scanQuestionsCap: 999 }), ["alpha/one.ts"], false);
  });
  assert.ok(getScannedFilePaths(db, repo).size > 0);

  const deleted = clearHistory(db);
  assert.ok(deleted.scanProgress >= 1);
  assert.equal(getScannedFilePaths(db, repo).size, 0, "scan progress must be fully cleared by reset history");
  db.close();
});
