import { test } from "node:test";
import assert from "node:assert/strict";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { execFileSync } from "child_process";
import { orderFilesRoundRobin, runScanWalk } from "../src/scan";
import { MAX_SCAN_CHUNK_LINES, splitFileIntoChunks, splitFileLines } from "../src/scanChunking";
import {
  clearHistory,
  getAllAnsweredConceptTags,
  getConceptTagGlobal,
  getScanCompletedFilePaths,
  insertEvent,
  openStore,
} from "../src/store";
import { testConfig } from "./helpers";

/**
 * Headless tests for `grasp scan`'s file-walk logic — chunk-granularity
 * ordering, capping, resumability, the mechanical ignore/generated-file/
 * binary/oversized skips, and the shared-memoization hard requirement — all
 * exercised directly against `runScanWalk`/`orderFilesRoundRobin`, without
 * going through the interactive review UI (which needs a real pty — see
 * scanPty.test.ts for that layer). See DECISIONS.md's `grasp scan: chunking
 * for large files` entry for the design this verifies.
 */

const FIXTURE_CLAUDE_DIR = path.resolve(process.cwd(), "test/fixtures/mock-claude");

function withMockClaude(env: Record<string, string>, fn: () => void): void {
  const originalPath = process.env.PATH;
  const originalEnv: Record<string, string | undefined> = {};
  for (const key of Object.keys(env)) originalEnv[key] = process.env[key];
  process.env.PATH = `${FIXTURE_CLAUDE_DIR}:${originalPath}`;
  Object.assign(process.env, env);
  try {
    fn();
  } finally {
    process.env.PATH = originalPath;
    for (const key of Object.keys(env)) {
      if (originalEnv[key] === undefined) delete process.env[key];
      else process.env[key] = originalEnv[key];
    }
  }
}

function mkTempDir(prefix: string): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), prefix));
}

function git(cwd: string, args: string[]): void {
  execFileSync("git", args, { cwd, stdio: "pipe" });
}

/**
 * A real git repo with tracked files spread across three top-level
 * directories plus a root-level file — enough to prove round-robin
 * directory spreading actually happened, not just plausible-looking file
 * counts. Also includes one lockfile (baseline-ignored) and one
 * self-declared generated file, both under their own directory, to prove
 * the mechanical skips work during a real walk without ever reaching the
 * judge.
 */
function initFixtureRepo(): string {
  const repo = mkTempDir("grasp-test-scan-repo-");
  git(repo, ["init", "-q"]);
  git(repo, ["config", "user.email", "test@example.com"]);
  git(repo, ["config", "user.name", "Test"]);

  const write = (rel: string, content: string) => {
    const full = path.join(repo, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content);
  };

  write("alpha/one.ts", "export function alphaOne() {\n  return 1;\n}\n");
  write("alpha/two.ts", "export function alphaTwo() {\n  return 2;\n}\n");
  write("beta/one.ts", "export function betaOne() {\n  return 3;\n}\n");
  write("beta/two.ts", "export function betaTwo() {\n  return 4;\n}\n");
  write("gamma/one.ts", "export function gammaOne() {\n  return 5;\n}\n");
  write("root.ts", "export function root() {\n  return 6;\n}\n");
  write("alpha/package-lock.json", '{"lockfileVersion": 1}');
  write("beta/generated.ts", "// Code generated by protoc-gen-ts. DO NOT EDIT.\nexport const x = 1;\n");

  git(repo, ["add", "-A"]);
  git(repo, ["commit", "-q", "-m", "initial"]);
  return repo;
}

function tempDbPath(): string {
  return path.join(mkTempDir("grasp-test-scan-db-"), "history.db");
}

function linesFile(n: number): string {
  const lines: string[] = [];
  for (let i = 1; i <= n; i++) lines.push(`// line ${i}`);
  return lines.join("\n") + "\n";
}

// --- orderFilesRoundRobin: pure ordering logic ------------------------------

test("orderFilesRoundRobin: interleaves across top-level directories instead of exhausting one first", () => {
  const paths = ["a/1.ts", "a/2.ts", "a/3.ts", "b/1.ts", "c/1.ts", "c/2.ts"];
  const ordered = orderFilesRoundRobin(paths);
  const dirs = ordered.map((p) => p.split("/")[0]);
  // Round-robin: a, b, c, a, c (b exhausted after its one file), a.
  assert.deepEqual(dirs, ["a", "b", "c", "a", "c", "a"]);
});

test("orderFilesRoundRobin: a root-level file gets its own group, not merged with any subdirectory", () => {
  const ordered = orderFilesRoundRobin(["root.ts", "a/1.ts"]);
  assert.equal(ordered.length, 2);
  assert.ok(ordered.includes("root.ts"));
  assert.ok(ordered.includes("a/1.ts"));
});

test("orderFilesRoundRobin: every input path appears exactly once in the output, none lost or duplicated", () => {
  const paths = ["a/1.ts", "a/2.ts", "b/1.ts", "b/2.ts", "b/3.ts", "c/1.ts"];
  const ordered = orderFilesRoundRobin(paths);
  assert.deepEqual([...ordered].sort(), [...paths].sort());
});

// --- runScanWalk: capping, ordering-in-practice, resumability --------------

test("runScanWalk: a capped run stops partway and actually spreads coverage across more than one top-level directory", () => {
  // "normal" mode always produces a "both" question (fresh concept tag per
  // call) — 2 real questions per chunk, not 1. With scanQuestionsCap=3, the
  // cap is checked before each chunk (see DECISIONS.md's "question caps
  // count real questions, not event-rows" entry): file 1's sole chunk
  // (count 0 < 3) proceeds and pushes the count to 2; file 2's sole chunk
  // (2 < 3) is still attempted and pushes the count to 4 — a legitimate
  // 1-question overshoot, accepted as a final state under "check before
  // generating, not after"; file 3 (4 >= 3) is blocked before any judge
  // call. So exactly 2 files get fully covered here, not 3.
  const repo = initFixtureRepo();
  const db = openStore(tempDbPath());
  const config = testConfig({ scanQuestionsCap: 3 });
  const sessionId = "scan-cap-test";

  withMockClaude({ GRASP_TEST_MOCK_MODE: "normal", GRASP_TEST_MOCK_COST: "0.001" }, () => {
    const ordered = orderFilesRoundRobin(["alpha/one.ts", "alpha/two.ts", "beta/one.ts", "beta/two.ts", "gamma/one.ts", "root.ts"]);
    const result = runScanWalk(db, repo, sessionId, config, ordered, false);
    assert.equal(result.capped, true, "the walk must stop once the cap is hit, not exhaust the whole list");
  });

  const completed = getScanCompletedFilePaths(db, repo);
  assert.equal(
    completed.size,
    2,
    "exactly 2 files should be fully covered — 2 'both' questions each, hitting the cap of 3 with a 1-question overshoot"
  );
  const dirsCovered = new Set([...completed].map((p) => p.split("/")[0]));
  assert.ok(dirsCovered.size > 1, `expected coverage across more than one top-level directory, got only: ${[...dirsCovered]}`);
  db.close();
});

test("runScanWalk: full=true bypasses the cap entirely, walking every file regardless of questionsPerSessionCap-style limits", () => {
  const repo = initFixtureRepo();
  const db = openStore(tempDbPath());
  // A cap of 1 would normally stop the walk after the first real question —
  // full=true must ignore it completely.
  const config = testConfig({ scanQuestionsCap: 1 });
  const files = ["alpha/one.ts", "alpha/two.ts", "beta/one.ts", "gamma/one.ts"];

  withMockClaude({ GRASP_TEST_MOCK_MODE: "normal", GRASP_TEST_MOCK_COST: "0.001" }, () => {
    const result = runScanWalk(db, repo, "scan-full-test", config, orderFilesRoundRobin(files), true);
    assert.equal(result.capped, false);
    assert.equal(result.filesTouched, files.length);
    assert.equal(result.chunksProcessed, files.length, "every file here is small — one chunk each");
  });

  assert.equal(getScanCompletedFilePaths(db, repo).size, files.length);
  db.close();
});

test("runScanWalk: a second run resumes from unscanned files, never re-asking about already-covered ones", () => {
  const repo = initFixtureRepo();
  const dbPath = tempDbPath();
  const allSourceFiles = ["alpha/one.ts", "alpha/two.ts", "beta/one.ts"];

  const db1 = openStore(dbPath);
  withMockClaude({ GRASP_TEST_MOCK_MODE: "normal", GRASP_TEST_MOCK_COST: "0.001" }, () => {
    runScanWalk(db1, repo, "scan-run-1", testConfig({ scanQuestionsCap: 1 }), orderFilesRoundRobin(allSourceFiles), false);
  });
  const completedAfterRun1 = getScanCompletedFilePaths(db1, repo);
  assert.equal(completedAfterRun1.size, 1);
  db1.close();

  const db2 = openStore(dbPath);
  const unscanned = allSourceFiles.filter((f) => !getScanCompletedFilePaths(db2, repo).has(f));
  assert.equal(unscanned.length, 2, "the resumed run must see exactly the files the first run didn't cover");
  withMockClaude({ GRASP_TEST_MOCK_MODE: "normal", GRASP_TEST_MOCK_COST: "0.001" }, () => {
    const result = runScanWalk(db2, repo, "scan-run-2", testConfig({ scanQuestionsCap: 999 }), orderFilesRoundRobin(unscanned), false);
    assert.equal(result.filesTouched, 2);
  });
  const completedAfterRun2 = getScanCompletedFilePaths(db2, repo);
  assert.equal(completedAfterRun2.size, 3, "all 3 files scanned across the two runs combined");

  const events = db2.prepare(`SELECT COUNT(*) AS n FROM events WHERE session_id IN ('scan-run-1', 'scan-run-2') AND question_type IS NOT NULL`).get() as { n: number };
  assert.equal(events.n, 3, "3 distinct real questions total, one per file, none re-asked");
  db2.close();
});

test("runScanWalk: ignore patterns and generated-file detection skip files without ever invoking claude", () => {
  const repo = initFixtureRepo();
  const db = openStore(tempDbPath());
  const config = testConfig({ scanQuestionsCap: 999 });

  // No mock claude on PATH at all — proves these two files never reach a
  // judge call. If either did, execFileSync("claude", ...) would fail
  // outright (no such binary), which would surface as an "error" miss row
  // instead of the two files being silently marked scanned with zero rows.
  const result = runScanWalk(db, repo, "scan-ignore-test", config, ["alpha/package-lock.json", "beta/generated.ts"], false);
  assert.equal(result.filesTouched, 2);
  assert.equal(result.chunksProcessed, 0, "mechanically-skipped files never reach a real generation call");

  const completed = getScanCompletedFilePaths(db, repo);
  assert.ok(completed.has("alpha/package-lock.json"));
  assert.ok(completed.has("beta/generated.ts"));

  const eventCount = (db.prepare(`SELECT COUNT(*) AS n FROM events`).get() as { n: number }).n;
  assert.equal(eventCount, 0, "neither file should have produced any events row — both were mechanically skipped");
  db.close();
});

test("runScanWalk: a binary file is skipped (marked scanned, no judge call)", () => {
  const repo = initFixtureRepo();
  fs.writeFileSync(path.join(repo, "binary.dat"), Buffer.from([0x00, 0x01, 0x02, 0xff, 0x00]));
  const db = openStore(tempDbPath());
  const config = testConfig({ scanQuestionsCap: 999 });

  runScanWalk(db, repo, "scan-binary-test", config, ["binary.dat"], false);

  assert.ok(getScanCompletedFilePaths(db, repo).has("binary.dat"));
  const eventCount = (db.prepare(`SELECT COUNT(*) AS n FROM events`).get() as { n: number }).n;
  assert.equal(eventCount, 0);
  db.close();
});

test("runScanWalk: a failed judge call (error) leaves the file unscanned for retry, not lost", () => {
  const repo = initFixtureRepo();
  const db = openStore(tempDbPath());
  const config = testConfig({ scanQuestionsCap: 999 });

  withMockClaude({ GRASP_TEST_MOCK_MODE: "error" }, () => {
    runScanWalk(db, repo, "scan-fail-test", config, ["alpha/one.ts"], false);
  });

  assert.equal(getScanCompletedFilePaths(db, repo).has("alpha/one.ts"), false, "a failed attempt must not be marked scanned");
  const missRow = db.prepare(`SELECT miss_reason, source FROM events WHERE session_id = 'scan-fail-test'`).get() as any;
  assert.equal(missRow.miss_reason, "error");
  assert.equal(missRow.source, "scan");
  db.close();
});

// --- Prompt 8: chunking for large files -------------------------------------

test("runScanWalk: a file over the chunk threshold splits into multiple real questions, each chunk's excerpt using absolute (not chunk-relative) line numbers", () => {
  const repo = initFixtureRepo();
  fs.writeFileSync(path.join(repo, "big.ts"), linesFile(MAX_SCAN_CHUNK_LINES + 50));
  const db = openStore(tempDbPath());
  const config = testConfig({ scanQuestionsCap: 999 });

  // A tiny custom mock: reports back the FIRST absolute line number it's
  // shown (parsed straight out of the prompt's own line-numbered content),
  // proving by construction that a chunk other than the first produces a
  // citation in the FILE's real numbering, not restarting at 1.
  const mockDir = mkTempDir("grasp-test-scan-chunk-mock-");
  fs.writeFileSync(
    path.join(mockDir, "claude"),
    `#!/usr/bin/env node
const args = process.argv.slice(2);
const prompt = args[args.indexOf("-p") + 1];
const lineMatch = prompt.match(/(\\d+)\\|/);
const firstLine = lineMatch ? parseInt(lineMatch[1], 10) : 1;
const result = {
  worthAsking: true,
  conceptTag: "chunk-concept-" + firstLine,
  questionConcept: "concept question for the chunk starting at " + firstLine,
  questionInstance: "instance question about the chunk starting at " + firstLine,
  sampleAnswerConcept: "sample concept answer",
  sampleAnswerInstance: "sample instance answer",
  conceptExplanation: "explanation",
  citedLineStart: firstLine,
  citedLineEnd: firstLine + 1
};
process.stdout.write(JSON.stringify({ total_cost_usd: 0.001, result: JSON.stringify(result), is_error: false }));
`,
    { mode: 0o755 }
  );

  const originalPath = process.env.PATH;
  process.env.PATH = `${mockDir}:${originalPath}`;
  let result: ReturnType<typeof runScanWalk>;
  try {
    result = runScanWalk(db, repo, "scan-chunk-test", config, ["big.ts"], false);
  } finally {
    process.env.PATH = originalPath;
  }

  assert.equal(result!.chunksProcessed, 2, "a file of MAX_SCAN_CHUNK_LINES + 50 lines must split into exactly 2 chunks");
  assert.ok(getScanCompletedFilePaths(db, repo).has("big.ts"), "the file's walk must be complete once both chunks are covered");

  const rows = db
    .prepare(`SELECT scan_excerpt_start_line, scan_excerpt_end_line FROM events WHERE session_id = 'scan-chunk-test' AND question_type IS NOT NULL ORDER BY id ASC`)
    .all() as Array<{ scan_excerpt_start_line: number; scan_excerpt_end_line: number }>;
  assert.equal(rows.length, 2, "each chunk must produce its own real question");
  assert.equal(rows[0].scan_excerpt_start_line, 1, "chunk 0's citation must start at the file's real line 1");
  assert.equal(
    rows[1].scan_excerpt_start_line,
    MAX_SCAN_CHUNK_LINES + 1,
    "chunk 1's citation must use the FILE's absolute line number, not restart at 1"
  );
  db.close();
});

test("splitFileLines: a trailing newline is not counted as an extra line", () => {
  assert.equal(splitFileLines("").length, 0, "a genuinely empty file has 0 lines, not 1");
  assert.equal(splitFileLines("a\nb\nc\n").length, 3, "3 real, newline-terminated lines must report 3, not 4");
  assert.equal(splitFileLines("a\nb\nc").length, 3, "a file whose last line ISN'T newline-terminated must still report the correct count");
  assert.equal(splitFileLines("a\nb\n\n").length, 3, "a genuine trailing blank line before EOF must still be counted");
});

test("splitFileIntoChunks: a file with exactly MAX_SCAN_CHUNK_LINES real lines must not produce a spurious extra near-empty final chunk", () => {
  // Regression test for the fileLines.length off-by-one: before the fix, a
  // newline-terminated file split via the raw `.split(/\r\n|\r|\n/)`
  // pattern reported one MORE line than it really had, so a file whose real
  // line count landed exactly on a MAX_SCAN_CHUNK_LINES boundary produced a
  // second, near-empty chunk consisting of nothing but the phantom trailing
  // blank "line" — a wasted judge call on nothing.
  const content = linesFile(MAX_SCAN_CHUNK_LINES);
  const fileLines = splitFileLines(content);
  assert.equal(fileLines.length, MAX_SCAN_CHUNK_LINES, "a file of exactly MAX_SCAN_CHUNK_LINES real lines must report exactly that many");

  const chunks = splitFileIntoChunks(fileLines);
  assert.equal(chunks.length, 1, "exactly MAX_SCAN_CHUNK_LINES real lines must still fit in a single chunk, not spill into a spurious second one");
  assert.equal(chunks[0].isFinal, true);
  assert.equal(chunks[0].lines.length, MAX_SCAN_CHUNK_LINES);
});

test("runScanWalk: a large multi-chunk file genuinely interleaves with small single-chunk files across passes, not one contiguous block", () => {
  const repo = mkTempDir("grasp-test-scan-interleave-repo-");
  git(repo, ["init", "-q"]);
  git(repo, ["config", "user.email", "test@example.com"]);
  git(repo, ["config", "user.name", "Test"]);
  const write = (rel: string, content: string) => {
    const full = path.join(repo, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content);
  };
  // 3 chunks: lines 1-400, 401-800, 801-900.
  write("big/file.ts", linesFile(2 * MAX_SCAN_CHUNK_LINES + 100));
  write("small1/a.ts", "// small file a\n");
  write("small2/b.ts", "// small file b\n");
  git(repo, ["add", "-A"]);
  git(repo, ["commit", "-q", "-m", "initial"]);

  const orderLogPath = path.join(mkTempDir("grasp-test-scan-order-log-"), "order.log");
  fs.writeFileSync(orderLogPath, "");
  const mockDir = mkTempDir("grasp-test-scan-order-mock-");
  fs.writeFileSync(
    path.join(mockDir, "claude"),
    `#!/usr/bin/env node
const fs = require("fs");
const args = process.argv.slice(2);
const prompt = args[args.indexOf("-p") + 1];
const fileMatch = prompt.match(/^File: (.+)$/m);
const lineMatch = prompt.match(/(\\d+)\\|/);
fs.appendFileSync(process.env.GRASP_TEST_ORDER_LOG, fileMatch[1] + ":" + lineMatch[1] + "\\n");
const tag = ("chunk-" + fileMatch[1] + "-" + lineMatch[1]).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
const result = {
  worthAsking: true,
  conceptTag: tag,
  questionConcept: "concept q",
  questionInstance: "instance q",
  sampleAnswerConcept: "sample concept",
  sampleAnswerInstance: "sample instance",
  conceptExplanation: "explanation",
  citedLineStart: parseInt(lineMatch[1], 10),
  citedLineEnd: parseInt(lineMatch[1], 10) + 1
};
process.stdout.write(JSON.stringify({ total_cost_usd: 0.001, result: JSON.stringify(result), is_error: false }));
`,
    { mode: 0o755 }
  );

  const db = openStore(tempDbPath());
  // Cap of 8: pass 1 covers big/chunk0 (0->2), small1 (2->4), small2 (4->6);
  // pass 2's first check (6<8) lets big/chunk1 through (6->8); the next
  // check (8>=8) then caps the walk before small1/small2 are re-visited
  // (already done) or big/chunk2 is reached.
  const config = testConfig({ scanQuestionsCap: 8 });
  const ordered = orderFilesRoundRobin(["big/file.ts", "small1/a.ts", "small2/b.ts"]);

  const originalPath = process.env.PATH;
  const originalOrderLog = process.env.GRASP_TEST_ORDER_LOG;
  process.env.PATH = `${mockDir}:${originalPath}`;
  process.env.GRASP_TEST_ORDER_LOG = orderLogPath;
  let result: ReturnType<typeof runScanWalk>;
  try {
    result = runScanWalk(db, repo, "scan-interleave-test", config, ordered, false);
  } finally {
    process.env.PATH = originalPath;
    if (originalOrderLog === undefined) delete process.env.GRASP_TEST_ORDER_LOG;
    else process.env.GRASP_TEST_ORDER_LOG = originalOrderLog;
  }
  assert.equal(result!.capped, true);

  const log = fs
    .readFileSync(orderLogPath, "utf-8")
    .trim()
    .split("\n")
    .filter((l) => l.length > 0);
  assert.deepEqual(
    log,
    ["big/file.ts:1", "small1/a.ts:1", "small2/b.ts:1", "big/file.ts:401"],
    "big/file.ts's second chunk must be preceded by BOTH small files' calls, not immediately follow its own first chunk"
  );
  db.close();
});

test("runScanWalk: a file over the new defensive processing ceiling is skipped with a visible message, marked fully scanned", () => {
  const repo = initFixtureRepo();
  // Import the ceiling indirectly via a file we know is well over it —
  // scan.ts's own MAX_SCAN_CEILING_LINES is intentionally not exported (an
  // internal implementation constant), so this constructs a file guaranteed
  // to exceed any reasonable ceiling instead of importing the exact number.
  fs.writeFileSync(path.join(repo, "huge.ts"), linesFile(25_000));
  const db = openStore(tempDbPath());
  const config = testConfig({ scanQuestionsCap: 999 });

  // No mock claude on PATH — an oversized file must never reach a judge call.
  const result = runScanWalk(db, repo, "scan-oversized-test", config, ["huge.ts"], false);

  assert.equal(result.oversizedSkips.length, 1);
  assert.equal(result.oversizedSkips[0].filePath, "huge.ts");
  assert.equal(result.oversizedSkips[0].lineCount, 25_000, "linesFile's trailing newline must not be counted as an extra line");
  assert.ok(getScanCompletedFilePaths(db, repo).has("huge.ts"), "an oversized file must still be marked fully scanned, same permanence as other skip categories");
  const eventCount = (db.prepare(`SELECT COUNT(*) AS n FROM events`).get() as { n: number }).n;
  assert.equal(eventCount, 0);
  db.close();
});

// --- the one hard, non-negotiable requirement: shared memoization ----------

test("runScanWalk: a concept mastered via a live diff question is skipped during a scan (shared memoization)", () => {
  const repo = initFixtureRepo();
  const db = openStore(tempDbPath());
  const config = testConfig({ scanQuestionsCap: 999 });

  // Seed a diff-sourced, answered concept tag — exactly what a real
  // `grasp review` answer produces (source defaults to "diff").
  insertEvent(
    db,
    {
      timestamp: new Date().toISOString(),
      repo,
      sessionId: "real-cc-session",
      diffHash: "abc",
      diffSummary: "1 file changed",
      questionConcept: "What is a mutex?",
      questionInstance: "Why did this diff use one?",
      questionType: "both",
      generationSource: "headless-claude-p",
      missReason: null,
      answerConcept: "a mutual exclusion lock",
      answerInstance: "to protect shared state",
      skipped: false,
      skipReason: null,
      costUsd: 0.001,
      diffFiles: [],
    },
    [{ tag: "mutex-vs-channel", answered: true }]
  );
  assert.equal(getConceptTagGlobal(db, "mutex-vs-channel", true).length, 1, "sanity check: the concept is recorded as answered");

  // The mock's "brand-new-concept-no-question" mode conveniently returns a
  // FIXED tag name — swap it for "mutex-vs-channel" via a small local mock
  // instead, so this test exercises the real already-answered branch of
  // runScanFileGeneration (instance-only, no concept question) rather than
  // the contract-violation branch that mode is actually for.
  const mockClaudeDir = fs.mkdtempSync(path.join(os.tmpdir(), "grasp-test-scan-memo-mock-"));
  fs.writeFileSync(
    path.join(mockClaudeDir, "claude"),
    `#!/usr/bin/env node
const result = {
  worthAsking: true,
  conceptTag: "mutex-vs-channel",
  questionConcept: "should never be asked again",
  questionInstance: "instance question about this file",
  sampleAnswerConcept: "should not appear",
  sampleAnswerInstance: "sample instance answer",
  conceptExplanation: "explanation",
  citedLineStart: 1,
  citedLineEnd: 2
};
process.stdout.write(JSON.stringify({ total_cost_usd: 0.001, result: JSON.stringify(result), is_error: false }));
`,
    { mode: 0o755 }
  );

  const originalPath = process.env.PATH;
  process.env.PATH = `${mockClaudeDir}:${originalPath}`;
  try {
    runScanWalk(db, repo, "scan-memo-test", config, ["alpha/one.ts"], false);
  } finally {
    process.env.PATH = originalPath;
  }

  const row = db.prepare(`SELECT question_concept, question_instance, question_type, sample_answer_concept FROM events WHERE session_id = 'scan-memo-test'`).get() as any;
  assert.equal(row.question_type, "instance", "the concept question must be suppressed — this concept was already mastered via a diff question");
  assert.equal(row.question_concept, null);
  assert.equal(row.sample_answer_concept, null);
  assert.equal(row.question_instance, "instance question about this file");
  db.close();
});

test("runScanWalk: a concept mastered via a scan question is skipped for a later diff-side generation (shared memoization, the other direction)", () => {
  const db = openStore(tempDbPath());
  // Seed a scan-sourced, answered concept tag.
  insertEvent(
    db,
    {
      timestamp: new Date().toISOString(),
      repo: "/tmp/whatever-repo",
      sessionId: "scan-abc123",
      diffHash: null,
      diffSummary: "some/file.ts",
      questionConcept: "What is recursion?",
      questionInstance: "Where does this file use it?",
      questionType: "both",
      generationSource: "headless-claude-p",
      missReason: null,
      answerConcept: "a function calling itself",
      answerInstance: "in the tree-walk helper",
      skipped: false,
      skipReason: null,
      costUsd: 0.001,
      diffFiles: null,
      source: "scan",
    },
    [{ tag: "recursion", answered: true }]
  );

  // getAllAnsweredConceptTags (what the diff-side judge prompt reads to
  // avoid re-teaching) must include this tag with no source filter at all.
  const answered: string[] = getAllAnsweredConceptTags(db);
  assert.ok(answered.includes("recursion"), "a concept mastered via grasp scan must show up in the diff side's own already-answered list");
  db.close();
});

// --- reset history clears scan progress too ---------------------------------

test("clearHistory: also wipes scan_progress, so a reset repo can be scanned from scratch", () => {
  const repo = initFixtureRepo();
  const db = openStore(tempDbPath());
  withMockClaude({ GRASP_TEST_MOCK_MODE: "normal", GRASP_TEST_MOCK_COST: "0.001" }, () => {
    runScanWalk(db, repo, "scan-reset-test", testConfig({ scanQuestionsCap: 999 }), ["alpha/one.ts"], false);
  });
  assert.ok(getScanCompletedFilePaths(db, repo).size > 0);

  const deleted = clearHistory(db);
  assert.ok(deleted.scanProgress >= 1);
  assert.equal(getScanCompletedFilePaths(db, repo).size, 0, "scan progress must be fully cleared by reset history");
  db.close();
});
