import * as fs from "fs";
import * as path from "path";
import { CapturedDiff, DiffFile, DiffHunk } from "./adapters/agentAdapter";
import { BASELINE_IGNORE_PATTERNS } from "./ignoreBaseline";
import { GraspConfig } from "./types";

/**
 * Purely mechanical pre-filtering (brief §5.2's mechanical half only — no
 * semantic "is this interesting" judgment lives here; see DECISIONS.md's
 * "Flagged-pattern filtering" entry from Phase 4's planning and the
 * formatting-only/filtered-diff-recording entries added in this phase).
 */

export type FilterReason =
  | "baseline_ignore"
  | "user_ignore_pattern"
  | "generated_file"
  | "formatting_only"
  | "below_min_threshold"
  | "above_max_threshold";

export type FileExclusionReason =
  | "baseline_ignore"
  | "user_ignore_pattern"
  | "generated_file"
  | "formatting_only";

export interface ExcludedFile {
  path: string;
  reason: FileExclusionReason;
}

export interface FilterResult {
  passed: boolean;
  reason: FilterReason | null;
  /**
   * Files that survived exclusion — what a future Phase 5 should actually
   * operate on. Empty whenever `passed` is false.
   */
  significantFiles: DiffFile[];
  excludedFiles: ExcludedFile[];
  totalChangedLines: number;
  maxSingleFileChangedLines: number;
}

// --- Ignore-pattern matching -------------------------------------------

/**
 * A pattern ending in "/" matches a directory anywhere in the path (e.g.
 * "node_modules/" matches "packages/a/node_modules/x.js"). Anything else
 * matches by exact basename or exact full relative path (e.g.
 * "package-lock.json" matches both "package-lock.json" and
 * "packages/a/package-lock.json"). No glob syntax — see DECISIONS.md's
 * "Ignore-pattern matching syntax" entry for why.
 */
export function matchesIgnorePattern(filePath: string, pattern: string): boolean {
  const normalizedPath = filePath.replace(/\\/g, "/").replace(/^\.\//, "");
  if (pattern.endsWith("/")) {
    const dirName = pattern.slice(0, -1);
    const dirSegments = normalizedPath.split("/").slice(0, -1);
    return dirSegments.includes(dirName);
  }
  const basename = normalizedPath.split("/").pop() ?? normalizedPath;
  return basename === pattern || normalizedPath === pattern;
}

function classifyIgnoreExclusion(filePath: string, config: GraspConfig): FileExclusionReason | null {
  if (BASELINE_IGNORE_PATTERNS.some((p) => matchesIgnorePattern(filePath, p))) {
    return "baseline_ignore";
  }
  if (config.ignorePatterns.some((p) => matchesIgnorePattern(filePath, p))) {
    return "user_ignore_pattern";
  }
  return null;
}

// --- Generated-file detection -------------------------------------------

/**
 * Common conventions generators (protobuf/gRPC, OpenAPI, ORMs, `git`
 * itself, etc.) use to mark a file as machine-written, checked
 * case-insensitively against a file's own added content rather than a
 * fixed path/extension list — README already advertises "generated files"
 * as excluded, but the only prior implementation was a small hardcoded
 * baseline path list (lockfiles, `dist/`, `build/`), which misses any
 * generated file living somewhere else, e.g. `src/api.generated.ts`. See
 * DECISIONS.md's "Generated-file content detection" entry.
 */
const GENERATED_FILE_MARKERS: RegExp[] = [
  /auto-?generated/i,
  /do not edit/i,
  /code generated by/i,
  /this file (?:is|was) automatically generated/i,
  /@generated\b/i,
];

/**
 * How many lines from the top of the NEW file a generated-file marker has
 * to appear within to count. These markers conventionally live in a header
 * comment at the very top of a file (see e.g. the protoc-gen-ts example
 * above) — this is a position-in-the-FILE check, not a position-in-the-diff
 * one; see `isFileGeneratedFromDiff`'s own comment for why that distinction matters.
 */
const GENERATED_FILE_HEADER_LINE_LIMIT = 5;

/**
 * Common single-line comment openers across the languages Grasp is likely to
 * see (`//`, `#`, `--`, `;`, `%`), C-style block-comment delimiters (`/*`,
 * `*` for a continuation line), HTML/XML (`<!--`), and Python/doc-string
 * triple quotes. A marker phrase is only treated as a generated-file
 * declaration when it appears on a line that is itself a comment (or
 * docstring) opener — see `isFileGeneratedFromDiff`'s own comment for why this
 * check exists.
 */
const COMMENT_LINE_PATTERN = /^(\/\/|\/\*|\*|#|--|;|%|<!--|"""|''')/;

/** Extracts the new-file starting line number `c` from a hunk header of the form `@@ -a[,b] +c[,d] @@`. Returns null if the header doesn't match the expected shape. */
function parseHunkNewFileStartLine(header: string): number | null {
  const match = header.match(/^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@/);
  return match ? parseInt(match[1], 10) : null;
}

/** Extracts the old-file starting line number `a` from a hunk header of the form `@@ -a[,b] +c[,d] @@`. Returns null if the header doesn't match the expected shape. */
function parseHunkOldFileStartLine(header: string): number | null {
  const match = header.match(/^@@ -(\d+)(?:,\d+)? \+\d+(?:,\d+)? @@/);
  return match ? parseInt(match[1], 10) : null;
}

/**
 * True if a generated-file marker appears among the diff's added lines
 * AND that line falls within the first `GENERATED_FILE_HEADER_LINE_LIMIT`
 * lines of the resulting NEW file — not merely within the first few added
 * lines of whichever hunk happens to appear first in the diff.
 *
 * Originally implemented as "check the first 5 added lines of the diff,
 * wherever they fall" — found by an independent test pass to be a broad
 * false positive: an ordinary hunk touching, say, line 100 of an existing
 * file (e.g. `throw new Error("Do not edit locked state")`, a normal
 * runtime guard, not a generator's header comment) was misclassified as
 * `generated_file` and its entire otherwise-meaningful change silently
 * discarded, purely because it happened to be the first hunk in that
 * particular diff. The actual convention these markers rely on (protobuf/
 * gRPC, OpenAPI, ORMs, `git` itself) is a comment at the top of the FILE,
 * not the top of whatever diff happens to touch it — so this now tracks
 * each hunk's own new-file line numbers (from its `@@ -a,b +c,d @@` header)
 * while walking its lines, and only tests a marker against lines whose
 * real position in the resulting file is within the header window. A hunk
 * whose header start is already past that window is skipped entirely
 * without inspecting its content, so a change deep in an existing file can
 * never trigger this regardless of what its first few added lines say.
 *
 * A second, independent false positive found by an independent test pass:
 * even restricted to the file's first 5 lines, an ordinary short file's
 * real code can contain marker phrasing that has nothing to do with a
 * generator declaring the file machine-written, e.g. a 5-line file whose
 * third line is `throw new Error("Do not edit locked state")` — an
 * executable runtime guard, not a header comment. The generator convention
 * these markers actually rely on (protobuf/gRPC, OpenAPI, ORMs, `git`
 * itself) is a COMMENT at the top of the file, so a marker only counts when
 * the line it appears on is itself a comment/docstring opener (see
 * `COMMENT_LINE_PATTERN`) — ordinary strings and executable statements
 * near the top of a small file can no longer suppress a real question.
 */
function markerLineMatches(rawLine: string): boolean {
  const trimmed = rawLine.trim();
  return COMMENT_LINE_PATTERN.test(trimmed) && GENERATED_FILE_MARKERS.some((re) => re.test(rawLine));
}

function isFileGeneratedFromDiff(file: DiffFile): boolean {
  // A deleted file has no resulting NEW file for the marker to live in —
  // walk the OLD-file line numbers over the removed lines instead. Found by
  // an independent test pass: deleting a tracked generated file (a normal
  // generator operation — regenerating obsolete output) previously reached
  // Claude uncaught, since this function only ever looked at ADDED lines and
  // `isFileGeneratedOnDisk` deliberately returns false once the file no
  // longer exists on disk. See DECISIONS.md's "Generated-file detection:
  // deletion case" entry.
  if (file.status === "deleted") {
    for (const h of file.hunks) {
      const startLine = parseHunkOldFileStartLine(h.header);
      if (startLine === null || startLine > GENERATED_FILE_HEADER_LINE_LIMIT) continue;

      let lineNo = startLine;
      for (const line of h.lines) {
        if (line.startsWith("-") && !line.startsWith("---")) {
          if (lineNo <= GENERATED_FILE_HEADER_LINE_LIMIT && markerLineMatches(line.slice(1))) {
            return true;
          }
          lineNo++;
        } else if (line.startsWith("+") && !line.startsWith("+++")) {
          // Added lines don't exist in the old file — they don't advance
          // the old-file line counter.
        } else {
          // Context line: present in both old and new file, advances the
          // old-file counter too.
          lineNo++;
        }
      }
    }
    return false;
  }

  for (const h of file.hunks) {
    const startLine = parseHunkNewFileStartLine(h.header);
    if (startLine === null || startLine > GENERATED_FILE_HEADER_LINE_LIMIT) continue;

    let lineNo = startLine;
    for (const line of h.lines) {
      if (line.startsWith("+") && !line.startsWith("+++")) {
        if (lineNo <= GENERATED_FILE_HEADER_LINE_LIMIT && markerLineMatches(line.slice(1))) {
          return true;
        }
        lineNo++;
      } else if (line.startsWith("-") && !line.startsWith("---")) {
        // Removed lines don't exist in the new file — they don't advance
        // the new-file line counter.
      } else {
        // Context line: present in both old and new file, advances the
        // new-file counter too.
        lineNo++;
      }
    }
  }
  return false;
}

/** How many bytes from the start of a file are read to look for a header marker — comfortably more than GENERATED_FILE_HEADER_LINE_LIMIT lines' worth even for long lines, without reading an entire (possibly huge) generated file into memory. */
const HEADER_READ_BYTES = 4096;

/**
 * Reads the first `GENERATED_FILE_HEADER_LINE_LIMIT` lines of `absPath` off
 * disk, or null if the file can't be read (doesn't exist, deleted,
 * permissions, etc — never throws).
 */
function readFileHeaderLines(absPath: string): string[] | null {
  let fd: number;
  try {
    fd = fs.openSync(absPath, "r");
  } catch {
    return null;
  }
  try {
    const buffer = Buffer.alloc(HEADER_READ_BYTES);
    const bytesRead = fs.readSync(fd, buffer, 0, HEADER_READ_BYTES, 0);
    return buffer.toString("utf-8", 0, bytesRead).split(/\r\n|\r|\n/).slice(0, GENERATED_FILE_HEADER_LINE_LIMIT);
  } catch {
    return null;
  } finally {
    fs.closeSync(fd);
  }
}

/**
 * Checks the CURRENT on-disk file (not the diff) for a header marker.
 * Fixes a release-blocking gap an independent test pass found: the
 * diff-only check above only sees a marker when the header line itself is
 * part of THIS diff's added lines, which is true the first time a generated
 * file is added but false for every later regeneration where the header is
 * unchanged and only the generated body below it changes — the normal case
 * for a generator rerun. Reading the file directly catches an unchanged
 * header regardless of what the diff touched. Returns false (never throws)
 * if the file can't be read, or if no `repoRoot` was given (e.g. tests that
 * exercise pure diff content with no real file on disk) — see
 * DECISIONS.md's "Generated-file detection: unchanged-header case" entry.
 */
function isFileGeneratedOnDisk(file: DiffFile, repoRoot: string | undefined): boolean {
  if (!repoRoot || file.status === "deleted") return false;
  const lines = readFileHeaderLines(path.join(repoRoot, file.path));
  if (!lines) return false;
  return lines.some(markerLineMatches);
}

export function isFileGenerated(file: DiffFile, repoRoot?: string): boolean {
  return isFileGeneratedFromDiff(file) || isFileGeneratedOnDisk(file, repoRoot);
}

// --- Formatting-only detection ------------------------------------------

/**
 * Collapses insignificant whitespace: trims the line and collapses any run
 * of internal whitespace to a single space. Reindentation, trailing
 * whitespace, and tabs-vs-spaces all normalize identically; anything that
 * changes actual tokens does not.
 */
function normalizeLine(line: string): string {
  return line.trim().replace(/\s+/g, " ");
}

/** A hunk's removed lines (with their `-` prefix stripped), normalized, in order. */
function normalizedRemovedLines(hunk: DiffHunk): string[] {
  return hunk.lines
    .filter((l) => l.startsWith("-") && !l.startsWith("---"))
    .map((l) => normalizeLine(l.slice(1)));
}

/** A hunk's added lines (with their `+` prefix stripped), normalized, in order. */
function normalizedAddedLines(hunk: DiffHunk): string[] {
  return hunk.lines
    .filter((l) => l.startsWith("+") && !l.startsWith("+++"))
    .map((l) => normalizeLine(l.slice(1)));
}

function arraysEqual(a: string[], b: string[]): boolean {
  return a.length === b.length && a.every((v, i) => v === b[i]);
}

/** Every character with any whitespace removed entirely — used only as the reflow fallback below, never as the primary comparison (see its call site's comment for why). */
function stripAllWhitespace(lines: string[]): string {
  return lines.join("").replace(/\s+/g, "");
}

/**
 * A hunk is formatting-only if its normalized removed-line sequence exactly
 * equals its normalized added-line sequence (same content, same order —
 * order matters so a real reordering of statements is never mistaken for
 * formatting). A hunk with no removed/added lines at all (shouldn't happen
 * in practice, but) counts as formatting-only vacuously.
 *
 * That per-line check requires the same NUMBER of lines on each side, so it
 * misses a common formatter behavior: reflowing one line across several
 * (or several into one) with no token change, e.g. `return input.trim();`
 * wrapped onto two lines. As a fallback specifically for that case (only
 * reached when the per-line check already failed), compare the removed and
 * added blocks with ALL whitespace stripped rather than just normalized —
 * if the character sequences match exactly, the line-break placement is the
 * only difference. This does mean a change that ONLY affects whitespace
 * *inside* a token boundary (e.g. `"a  b"` -> `"a b"` in a string literal)
 * would also be misclassified as formatting-only; accepted as a rare,
 * low-stakes edge case for a mechanical pre-filter — see DECISIONS.md's
 * "Formatter-reflow detection" entry.
 */
function isHunkFormattingOnly(hunk: DiffHunk): boolean {
  const removedLines = normalizedRemovedLines(hunk);
  const addedLines = normalizedAddedLines(hunk);
  if (arraysEqual(removedLines, addedLines)) return true;
  const removedFlat = stripAllWhitespace(removedLines);
  const addedFlat = stripAllWhitespace(addedLines);
  return removedFlat.length > 0 && removedFlat === addedFlat;
}

/** A file is formatting-only only if every one of its hunks is. */
export function isFileFormattingOnly(file: DiffFile): boolean {
  if (file.hunks.length === 0) return false;
  return file.hunks.every(isHunkFormattingOnly);
}

// --- Main filter ----------------------------------------------------------

function pickEmptyReason(excludedFiles: ExcludedFile[]): FilterReason {
  // Priority: a user-specified pattern is the most intentional signal, then
  // the baseline list, then an explicit "generated" self-declaration, then
  // formatting-only (the most inferred of the four). Only matters when a
  // multi-file diff is emptied by a mix of reasons — none of Phase 4's own
  // verification scenarios hit this, but the order needs to be defined
  // rather than left to iteration order.
  if (excludedFiles.some((f) => f.reason === "user_ignore_pattern")) return "user_ignore_pattern";
  if (excludedFiles.some((f) => f.reason === "baseline_ignore")) return "baseline_ignore";
  if (excludedFiles.some((f) => f.reason === "generated_file")) return "generated_file";
  return "formatting_only";
}

/**
 * Applies Phase 4's mechanical filter to a captured diff. Two file-level
 * exclusion passes run first (ignore patterns, then formatting-only),
 * producing a "significant files" set; size thresholds are then evaluated
 * against ONLY that remaining set — so a file excluded by either pass
 * doesn't count toward or against the size thresholds. See DECISIONS.md's
 * "Diff-size thresholds: per-file exclusion, not whole-diff" entry.
 */
export function evaluateCapturedDiff(diff: CapturedDiff, config: GraspConfig): FilterResult {
  const excludedFiles: ExcludedFile[] = [];
  const significantFiles: DiffFile[] = [];

  for (const file of diff.files) {
    const ignoreReason = classifyIgnoreExclusion(file.path, config);
    if (ignoreReason) {
      excludedFiles.push({ path: file.path, reason: ignoreReason });
      continue;
    }
    if (isFileGenerated(file, diff.repo)) {
      excludedFiles.push({ path: file.path, reason: "generated_file" });
      continue;
    }
    if (isFileFormattingOnly(file)) {
      excludedFiles.push({ path: file.path, reason: "formatting_only" });
      continue;
    }
    significantFiles.push(file);
  }

  if (significantFiles.length === 0) {
    return {
      passed: false,
      reason: pickEmptyReason(excludedFiles),
      significantFiles: [],
      excludedFiles,
      totalChangedLines: 0,
      maxSingleFileChangedLines: 0,
    };
  }

  const fileSizes = significantFiles.map((f) => f.insertions + f.deletions);
  const totalChangedLines = fileSizes.reduce((sum, n) => sum + n, 0);
  const maxSingleFileChangedLines = Math.max(...fileSizes);

  const { minChangedLines, maxTotalChangedLines, maxSingleFileChangedLines: maxSingleFileCap } =
    config.diffThresholds;

  if (totalChangedLines > maxTotalChangedLines || maxSingleFileChangedLines > maxSingleFileCap) {
    return {
      passed: false,
      reason: "above_max_threshold",
      significantFiles: [],
      excludedFiles,
      totalChangedLines,
      maxSingleFileChangedLines,
    };
  }

  const anyFileClearsMinimum = fileSizes.some((size) => size >= minChangedLines);
  if (!anyFileClearsMinimum) {
    return {
      passed: false,
      reason: "below_min_threshold",
      significantFiles: [],
      excludedFiles,
      totalChangedLines,
      maxSingleFileChangedLines,
    };
  }

  return {
    passed: true,
    reason: null,
    significantFiles,
    excludedFiles,
    totalChangedLines,
    maxSingleFileChangedLines,
  };
}
